[package]
name = "nagad_sdk"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Junaid433/nagad_sdk/"
lisence = "MIT"

[dependencies]
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
rand = "0.8"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rsa = { version = "0.9", features = ["sha2", "pem"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
sha2 = "0.10"
thiserror = "1.0"
url = "2.5"